filename aaa 'C:\Users\vr02477\Desktop\whas500.dat';
data whas500;
infile aaa;
input id age gender hr sysbp diasbp bmi cvd afb sho chf av3 miord mitype year admitdateHospital$ disdate$ fdate$ los dstat lenfol fstat;
bmi12 = bmi**(-2);
bmifp1 = (bmi/10)**2;
bmifp2 = (bmi/10)**3;
ga=gender*age;
run;
proc print data=whas500;
var lenfol bmi;
run;
proc phreg data = whas500 ;
model lenfol*fstat(0) = bmifp1 bmifp2 age hr diasbp gender chf ga /risklimits alpha=0.1;
id id;
output out=f64 ressco = bmifp1_r bmifp2_r age_r hr_r diasbp_r gender_r chf_r ga_r;
run;

filename aaa 'C:\Users\vr02477\Desktop\uissurv.dat';
data uis;
infile aaa;
input id age becktota hercoc ivhx ndrugtx race treat site los time censor;
run;
proc phreg data = uis ;
model time*censor(0) = age becktota hercoc ivhx ndrugtx race treat site los /risklimits alpha=0.1;
id id;
output out=f64 ressco = age becktota hercoc ivhx ndrugtx race treat site los;
run;
filename aaa 'C:\Users\vr02477\Desktop\uissurv.dat';
data uis;
infile aaa;
input id age becktota hercoc ivhx ndrugtx race treat site los time censor;
run;
proc phreg data = uis ;
model time*censor(0) = age becktota ivhx ndrugtx race treat site los /risklimits alpha=0.1;
id id;
output out=f64 ressco = age becktota ivhx ndrugtx race treat site los;
run;
filename aaa 'C:\Users\vr02477\Desktop\uissurv.dat';
data uis;
infile aaa;
input id age becktota hercoc ivhx ndrugtx race treat site los time censor;
run;
proc phreg data = uis ;
model time*censor(0) = age ivhx ndrugtx race treat site los /risklimits alpha=0.1;
id id;
output out=f64 ressco = age ivhx ndrugtx race treat site los;
run;
filename aaa 'C:\Users\vr02477\Desktop\uissurv.dat';
data uis;
infile aaa;
input id age becktota hercoc ivhx ndrugtx race treat site los time censor;
run;
ods graphics on;
proc phreg data = uis ;
model time*censor(0) = age ivhx ndrugtx race site los /risklimits alpha=0.1;
id id;
output out=f64 ressco = age ivhx ndrugtx race site los;
run;

proc phreg data=uis plot(overlay)=survival;
   model time*censor(0) = age ivhx ndrugtx race site los /risklimits alpha=0.1;
   baseline covariates=uis out=_null_;
run;
