* Encoding: UTF-8.
REGRESSION
/MISSING LISTWISE
/STATISTICS COEFF OUTS CI(95) R ANOVA
/CRITERIA=PIN(.05) POUT(.10)
/NOORIGIN
/DEPENDENT SumPss
/METHOD=ENTER sex age smoke
/SCATTERPLOT=(*ZRESID ,*ZPRED)
/RESIDUALS HISTOGRAM(ZRESID).

CORRELATIONS
/VARIABLES=SumPss sex age smoke
/PRINT=TWOTAIL NOSIG
/MISSING=PAIRWISE.

REGRESSION
/MISSING LISTWISE
/STATISTICS COEFF OUTS CI(95) R ANOVA
/CRITERIA=PIN(.05) POUT(.10)
/NOORIGIN
/DEPENDENT SumPss
/METHOD=ENTER sex age smoke.


